apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      — name: nginx
        image: nginx
        ports:
        — containerPort: 80
        resources:
          limits:
            cpu: 0.4m
            memory: 128Mi
          requests:
            cpu: 0.1m
            memory: 128Mi
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /index.html
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        


